#server
server :
  port : 8200

spring:
  application:
    name: movie_ribbon

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true