server:
  port: 8000
spring:
  application:
    name: base-config
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/itmuch/spring-cloud-config-repo      # 配置Git仓库的地址
          username:                                                         # Git仓库的账号
          password:
      label: master
      profile: dev







