#server
server :
  port : 8200

spring:
  application:
    name: movie_ribbon

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#yml配置负载均衡策略
movie_ribbon:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    
